### ISSUE TITLE
New Release with MIT?

### ISSUE THREAD

**Issue by turtletech** [servel333/vogels-promisified#3]
Hi there,

I would like to use vogels-promisified with the latest MIT license. Could you tag a separate release for the current head with the updated license?

Thanks!

**Comment by servel333** [comment]
Is there a newer MIT licence than I'm using?

**Comment by svanzoest** [comment]
i think this is a request to do a release with tag.
Latest is currently https://github.com/servel333/vogels-promisified/releases/tag/2.2.3

**Comment by servel333** [comment]
Now I understand

**Comment by servel333** [comment]
Done and published to NPM

https://github.com/servel333/vogels-promisified/tree/2.2.4
https://www.npmjs.com/package/vogels-promisified
